<?php
    $this->headScript()->appendFile($this->basePath() . '/lib/js/momentjs/moment-with-locales.min.js');
    $this->headScript()->appendFile($this->basePath() . '/js/application/aluno/index.js');
?>

<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('home') ?>">Início</a></li>
    <li><a href="<?php echo $this->url('psicologia') ?>">Psicologia</a></li>
    <li class="active">Agendamento</li>
</ol>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <h3>Agendamentos</h3>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Data</th>
                    <th>Hora de Início</th>
                    <th>Hora de Término</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

            <?php foreach($list as $item): ?>

                <tr>
                    <td>
                        <?php echo $item['data']; ?>
                    </td>
                    <td>
                        <?php echo $item['hora_inicio']; ?>
                    </td>
                    <td>
                        <?php echo $item['hora_fim']; ?>
                    </td>
                    <td>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
