<?php
    $this->headLink()->appendStylesheet($this->basePath() . '/lib/css/alertify/alertify.min.css');
    $this->headLink()->appendStylesheet($this->basePath() . '/lib/css/alertify/themes/bootstrap.min.css');

    $this->headScript()->appendFile($this->basePath() . '/lib/js/alertify/alertify.min.js');
    $this->headScript()->appendFile($this->basePath() . '/lib/js/alertify/alertify.config.js');
    $this->headScript()->appendFile($this->basePath() . '/js/admin/cargo/index.js');
?>

<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('home') ?>">Início</a></li>
    <li><a href="<?php echo $this->url('admin') ?>">Painel Adminstrativo</a></li>
    <li class="active">Cargo</li>
</ol>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <h3>Cargo</h3>
    </div>
    <div class="col-sm-6 col-md-6">
        <div class="btn-group pull-right">
            <a href="<?php echo $this->url('cargo', array('action' => 'criar')) ?>" class="btn btn-primary btn-lg">
                <i class="fa fa-plus"></i>
                Cargo
            </a>
        </div>
    </div>
</div>

<hr/>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <form method="get" role="form">
            <div class="row">
                <div class="col-sm-8 col-md-6">
                    <input type="text" name="restricao" autofocus="autofocus" value="<?php echo $this->restricao ?>"
                           class="form-control" placeholder="Buscar...">
                </div>
                <div class="col-sm-3 col-md-3">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <?php
            $count = count($list);
            echo $this->partial('partials/paginacao/paginacao', array(
                'pagina' => (int) $this->pagina,
                'route' => 'cargo',
                'count' => $count,
                'restricao' => $this->restricao
            ));
        ?>
    </div>
</div>

<hr>

<?php if (count($list) > 0): ?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>CÓD.</th>
                    <th>Descrição</th>
                    <th style="width: 120px;">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($list as $item): ?>
                <tr>
                    <td><?php echo $item->getId() ?></td>
                    <td><?php echo $item->getDescricao() ?></td>
                    <td>
                        <div class="btn-group pull-right">

                            <a href="<?php echo $this->url('cargo',
                                    array('action' => 'editar', 'id' => $item->getId())); ?>"
                               class="btn btn-default" rel="tooltip" title="Editar">
                                <i class="fa fa-edit"></i>
                            </a>

                            <a href="<?php echo $this->url('cargo',
                                    array('action' => 'deletar', 'id' => $item->getId())); ?>"
                               class="btn btn-danger deletar" rel="tooltip" title="Deletar">
                                <i class="fa fa-times"></i>
                            </a>

                        </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        
    </div>
</div>
<?php else: ?>
<div class="alert alert-info">
    <p>Nenhum registro encontrado.</p>
</div>
<?php endif; ?>

<div class="row">
    <div class="col-md-6 col-md-offset-6">
        <?php
            echo $this->partial('partials/paginacao/paginacao', array(
                'pagina' => (int) $this->pagina,
                'route' => 'usuario',
                'count' => $count,
                'restricao' => $this->restricao
            ));
        ?>
    </div>
</div>
