<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Core\Module'                        => __DIR__ . '/Module.php',
    'Core\Model\TimeStampedEntity'       => __DIR__ . '/src/Core/Model/TimeStampedEntity.php',
    'Core\Model\Entity'                  => __DIR__ . '/src/Core/Model/Entity.php',
    'Core\Model\EntityException'         => __DIR__ . '/src/Core/Model/EntityException.php',
    'Core\Acl\Builder'                   => __DIR__ . '/src/Core/Acl/Builder.php',
    'Core\Service\Service'               => __DIR__ . '/src/Core/Service/Service.php',
    'Core\Service\Receita\ConsultarCnpj' => __DIR__ . '/src/Core/Service/Receita/ConsultarCnpj.php',
    'Core\Controller\Paginacao'          => __DIR__ . '/src/Core/Controller/Paginacao.php',
    'Core\Controller\ActionController'   => __DIR__ . '/src/Core/Controller/ActionController.php',
    'Core\Db\AdapterServiceFactory'      => __DIR__ . '/src/Core/Db/AdapterServiceFactory.php',
    'Core\Db\Service\PdoResourceFactory' => __DIR__ . '/src/Core/Db/Service/PdoResourceFactory.php',
    'Core\Db\TableGateway'               => __DIR__ . '/src/Core/Db/TableGateway.php',
    'Core\View\Helper\Session'           => __DIR__ . '/src/Core/View/Helper/Session.php',
    'Core\Test\ServiceTestCase'          => __DIR__ . '/src/Core/Test/ServiceTestCase.php',
    'Core\Test\TestCase'                 => __DIR__ . '/src/Core/Test/TestCase.php',
    'Core\Test\ModelTestCase'            => __DIR__ . '/src/Core/Test/ModelTestCase.php',
    'Core\Test\ControllerTestCase'       => __DIR__ . '/src/Core/Test/ControllerTestCase.php',
    'Core\Filter\NumberFormat'           => __DIR__ . '/src/Core/Filter/NumberFormat.php',
    'Core\Security\Security'             => __DIR__ . '/src/Core/Security/Security.php',
);
