<?php
    $this->headLink()->prependStylesheet($this->basePath() . '/css/grid-menu.css')
?>

<ol class="breadcrumb">
    <li class="active">Psicologia</li>
</ol>

<div class="row">
    <div class="col-md-12">
        <ul class="grid-menu">

            <li rel="tooltip" title="Acompanhamento">
                <a href="<?php echo $this->url('acompanhamento') ?>">
                    <img src="<?php echo $this->basePath() . '/images/psicologia/index/index/acompanhamento.png' ?>"
                         alt="Acompanhamento" class="center"/>
                </a>
            </li>

            <li rel="tooltip" title="Aluno">
                <a href="<?php echo $this->url('aluno') ?>">
                    <img src="<?php echo $this->basePath() . '/images/application/index/index/aluno.png' ?>"
                         alt="Aluno" class="center"/>
                </a>
            </li>

        </ul>
    </div>
</div>
