<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Psicologia\Controller\IndexController'          => __DIR__ . '/src/Psicologia/Controller/IndexController.php',
    'Psicologia\Controller\AcompanhamentoController' => __DIR__ . '/src/Psicologia/Controller/AcompanhamentoController.php',
    'Psicologia\Form\AcompanhamentoForm'             => __DIR__ . '/src/Psicologia/Form/AcompanhamentoForm.php',
    'Psicologia\Form\AcompanhamentoFilter'           => __DIR__ . '/src/Psicologia/Form/AcompanhamentoFilter.php',
    'Psicologia\Module'                              => __DIR__ . '/Module.php',
);
