<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'psicologia/index/index'           => __DIR__ . '/view/psicologia/index/index.phtml',
    'psicologia/acompanhamento/index'  => __DIR__ . '/view/psicologia/acompanhamento/index.phtml',
    'psicologia/acompanhamento/salvar' => __DIR__ . '/view/psicologia/acompanhamento/salvar.phtml',
);
