<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'partials/acompanhamento-individual/salvar/toolbar' => __DIR__ . '/view/partials/acompanhamento-individual/salvar/toolbar.phtml',
    'psicologia/acompanhamento-individual/index'        => __DIR__ . '/view/psicologia/acompanhamento-individual/index.phtml',
    'psicologia/acompanhamento-individual/salvar'       => __DIR__ . '/view/psicologia/acompanhamento-individual/salvar.phtml',
    'psicologia/acompanhamento/index'                   => __DIR__ . '/view/psicologia/acompanhamento/index.phtml',
    'psicologia/acompanhamento/detalhes'                => __DIR__ . '/view/psicologia/acompanhamento/detalhes.phtml',
    'psicologia/acompanhamento/salvar'                  => __DIR__ . '/view/psicologia/acompanhamento/salvar.phtml',
    'psicologia/index/index'                            => __DIR__ . '/view/psicologia/index/index.phtml',
    'psicologia/agendamento/index'                      => __DIR__ . '/view/psicologia/agendamento/index.phtml',
    'psicologia/agendamento/salvar'                     => __DIR__ . '/view/psicologia/agendamento/salvar.phtml',
);
