<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Admin\Module'                         => __DIR__ . '/Module.php',
    'Admin\Form\CargoFilter'               => __DIR__ . '/src/Admin/Form/CargoFilter.php',
    'Admin\Form\CargoForm'                 => __DIR__ . '/src/Admin/Form/CargoForm.php',
    'Admin\Form\ServidorForm'              => __DIR__ . '/src/Admin/Form/ServidorForm.php',
    'Admin\Form\ProfissaoFilter'           => __DIR__ . '/src/Admin/Form/ProfissaoFilter.php',
    'Admin\Form\ProfissaoForm'             => __DIR__ . '/src/Admin/Form/ProfissaoForm.php',
    'Admin\Controller\IndexController'     => __DIR__ . '/src/Admin/Controller/IndexController.php',
    'Admin\Controller\ServidorController'  => __DIR__ . '/src/Admin/Controller/ServidorController.php',
    'Admin\Controller\CargoController'     => __DIR__ . '/src/Admin/Controller/CargoController.php',
    'Admin\Controller\ProfissaoController' => __DIR__ . '/src/Admin/Controller/ProfissaoController.php',
);
