<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'admin/profissao/index'  => __DIR__ . '/view/admin/profissao/index.phtml',
    'admin/profissao/salvar' => __DIR__ . '/view/admin/profissao/salvar.phtml',
    'admin/index/index'      => __DIR__ . '/view/admin/index/index.phtml',
);
