<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'admin/servidor/index'   => __DIR__ . '/view/admin/servidor/index.phtml',
    'admin/servidor/salvar'  => __DIR__ . '/view/admin/servidor/salvar.phtml',
    'admin/profissao/index'  => __DIR__ . '/view/admin/profissao/index.phtml',
    'admin/profissao/salvar' => __DIR__ . '/view/admin/profissao/salvar.phtml',
    'admin/index/index'      => __DIR__ . '/view/admin/index/index.phtml',
    'admin/cargo/index'      => __DIR__ . '/view/admin/cargo/index.phtml',
    'admin/cargo/salvar'     => __DIR__ . '/view/admin/cargo/salvar.phtml',
);
