<?php
    $this->headScript()->appendFile($this->basePath() . '/lib/js/momentjs/moment-with-locales.min.js');
    $this->headScript()->appendFile($this->basePath() . '/js/psicologia/acompanhamento/detalhes.js');
?>

<style media="screen">
    .divider {
        margin-top: 10px;
    }
</style>

<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('home') ?>">Início</a></li>
    <li><a href="<?php echo $this->url('psicologia') ?>">Psicologia</a></li>
    <li><a href="<?php echo $this->url('acompanhamento') ?>">Acompanhamento</a></li>
    <li class="active">Detalhes</li>
</ol>

<div class="row">
    <div class="col-md-12">
        <div class="btn-group pull-right">
            <a href="<?php echo $this->url('acompanhamento', array(
                'action' => 'editar',
                'id' => $id
            )) ?>" class="btn btn-default">
                <i class="fa fa-edit"></i> Editar
            </a>
            <a href="<?php echo $this->url('acompanhamento-individual', array(
                'action' => 'criar',
                'id_acompanhamento' => $id
            )) ?>" class="btn btn-primary">
                <i class="fa fa-plus"></i> Acompanhamento Individual
            </a>
        </div>
    </div>
</div>

<h4 class="text-center">FICHA DE ACOMPANHAMENTO DO SERVIÇO DE PSICOLOGIA</h4>
<h4 class="text-center"><?php echo $obj['data_criacao'] ?></h4>
<hr/>

<h4>I. Dados de Identificação</h4>

<div class="row">
    <div class="col-md-6">
        <label>Nome</label>
        <div>
            <?php echo $obj['nome']; ?>
        </div>
    </div>
    <div class="col-md-1">
        <label>Sexo</label>
        <div>
            <?php echo $obj['sexo']; ?>
        </div>
    </div>
    <div class="col-md-2">
        <label>Data de Nascimento</label>
        <div>
            <?php echo $obj['dt_nascimento']; ?>
        </div>
    </div>
    <div class="col-md-2">
        <label>Idade</label>
        <div>
            <?php echo $obj['idade']; ?>
        </div>
    </div>
</div>

<div class="row divider">
    <div class="col-md-3">
        <label>Estado Civil</label>
        <div>
            <?php echo $obj['estado_civil']; ?>
        </div>
    </div>
    <div class="col-md-3">
        <label>Está trabalhando atualmente?</label>
        <div>
            <?php if ($obj['fl_ativo']): ?>
                <span class="label label-success">Sim</span>
            <?php else: ?>
                <span class="label label-danger">Não</span>
            <?php endif; ?>

            <?php echo $obj['profissao']; ?>
        </div>
    </div>
    <div class="col-md-3">
        <label>Curso</label>
        <div>
            <?php echo $obj['curso']; ?>
        </div>
    </div>
    <div class="col-md-3">
        <label>Período</label>
        <div>
            <?php echo $obj['periodo']; ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <hr>

        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Endereço</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($enderecos as $item): ?>
                    <tr>
                        <td>
                            <?php echo $item['logradouro'] ?>,
                            n. <?php echo $item['numero'] ?> -
                            <?php echo $item['cep'] ?> -
                            <?php echo $item['cidade'] ?>,
                            <?php echo $item['bairro'] ?> -
                            <?php echo $item['sigla'] ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <hr>

        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Contato</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-md-6">
        <h4>II. Dados familiares</h4>
    </div>
    <div class="col-md-6">
        <div class="btn-group pull-right">
            <a href="#" class="btn btn-info">
                <i class="fa fa-group"></i>
                Mostrar Genograma
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">

        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Telefone</th>
                    <th>Profissão</th>
                    <th>Parentesco</th>
                    <th>Mora na mesma casa?</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($familiares as $item): ?>
                    <tr>
                        <td><?php echo $item['nome'] ?></td>
                        <td><?php echo $item['idade'] ?></td>
                        <td><?php echo 'null' ?></td>
                        <td><?php echo $item['profissao'] ?></td>
                        <td><?php echo $item['grau_parentesco'] ?></td>
                        <td>
                            <?php if($item['flMora']): ?>
                                <span class="label label-success">Sim</span>
                            <?php else: ?>
                                <span class="label label-danger">Não</span>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-md-12">
        <h4>III. Motivo da Consulta</h4>

        <?php if($obj['motivo']): ?>
            <div>
                <?php echo $obj['motivo']; ?>
            </div>
        <?php else: ?>
            <div>
                <i>Nenhum motivo definido.</i>
            </div>
        <?php endif; ?>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-md-6">
        <h4>VI. Encaminhamento</h4>

        <?php if($obj['encaminhado']): ?>
            <label>Foi encaminhado por</label>
            <div>
                <?php echo $obj['encaminhado']; ?>
            </div>
        <?php else: ?>
            <div>
                Demanda espontânea
            </div>
        <?php endif; ?>
    </div>
    <div class="col-md-6">
        <h4>VII. Situação escolar</h4>

        <?php echo $obj['situacao_escolar']; ?>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-md-6">
        <h4>XI. Quadro de acompanhamento</h4>

        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th># Encontro</th>
                    <th>Data</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($acompanhamentos as $item): ?>
                <tr>
                    <td><?php echo $item['numeroEncontro']; ?></td>
                    <td>
                        <span class="moment"
                            title="<?php echo $item['dataCriacao']->format('d/m/Y H:i'); ?>">
                            <?php echo $item['dataCriacao']->format('Y-m-d H:i:s'); ?>
                        </span>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->url('acompanhamento-individual', array(
                                'action' => 'editar',
                                'id' => $item['id'],
                                'id_acompanhamento' => $id
                            )) ?>"
                            class="btn btn-default">
                                <i class="fa fa-edit"></i> Editar
                            </a>
                        </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
