<?php
    $this->headScript()->appendFile($this->basePath() . '/lib/js/momentjs/moment-with-locales.min.js');
    $this->headScript()->appendFile($this->basePath() . '/js/psicologia/acompanhamento/index.js');
?>

<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('psicologia') ?>">Psicologia</a></li>
    <li class="active">Acompanhamento</li>
</ol>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <h3>Acompanhamento</h3>
    </div>
    <div class="col-sm-6 col-md-6">
        <div class="btn-group pull-right">
            <a href="<?php echo $this->url('acompanhamento', array('action' => 'criar')) ?>" class="btn btn-primary btn-lg">
                <i class="fa fa-plus"></i>
                Acompanhamento
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Aluno</th>
                    <th>Curso</th>
                    <th>Situação Escolar</th>
                    <th>Criação</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($list as $item): ?>
                <tr>
                    <td>
                        <?php echo $item['matricula']; ?>
                        /
                        <?php echo $item['nome']; ?>
                    </td>
                    <td>
                        <?php echo $item['curso']; ?>
                        /
                        <?php echo $item['periodo']; ?>
                    </td>
                    <td>
                        <?php echo $item['situacaoEscolar']; ?>
                    </td>
                    <td>
                        <span class="moment"
                            title="<?php echo $item['dataCriacao']->format('d/m/Y H:i'); ?>">
                            <?php echo $item['dataCriacao']->format('Y-m-d H:i:s'); ?>
                        </span>
                    </td>
                    <td>
                        <div class="btn-group">
                            <a href="<?php echo $this->url('acompanhamento', array(
                                'action' => 'detalhes',
                                'id' => $item['id']
                            )) ?>" class="btn btn-default">
                                <i class="fa fa-tasks"></i> Detalhes
                            </a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
