
<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('home') ?>">Início</a></li>
    <li><a href="<?php echo $this->url('psicologia') ?>">Psicologia</a></li>
    <li class="active">Acompanhamento</li>
</ol>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <h3>Acompanhamento</h3>
    </div>
    <div class="col-sm-6 col-md-6">
        <div class="btn-group pull-right">
            <a href="<?php echo $this->url('acompanhamento', array('action' => 'criar')) ?>" class="btn btn-primary btn-lg">
                <i class="fa fa-plus"></i>
                Acompanhamento
            </a>
        </div>
    </div>
</div>
