<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Entity\UsuarioRepository'           => __DIR__ . '/src/Application/Entity/UsuarioRepository.php',
    'Application\View\Helper\FormatarNumero'         => __DIR__ . '/src/Application/View/Helper/FormatarNumero.php',
    'Application\View\Helper\LabelStatus'            => __DIR__ . '/src/Application/View/Helper/LabelStatus.php',
    'Application\Service\Auth'                       => __DIR__ . '/src/Application/Service/Auth.php',
    'Application\Controller\IndexController'         => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Controller\UsuarioController'       => __DIR__ . '/src/Application/Controller/UsuarioController.php',
    'Application\Controller\AuthController'          => __DIR__ . '/src/Application/Controller/AuthController.php',
    'Application\Model\Usuario'                      => __DIR__ . '/src/Application/Model/Usuario.php',
    'Application\Model\UsuarioTable'                 => __DIR__ . '/src/Application/Model/UsuarioTable.php',
    'Application\Form\UsuarioFilter'                 => __DIR__ . '/src/Application/Form/UsuarioFilter.php',
    'Application\Form\UsuarioForm'                   => __DIR__ . '/src/Application/Form/UsuarioForm.php',
    'Application\Form\LoginFilter'                   => __DIR__ . '/src/Application/Form/LoginFilter.php',
    'Application\Form\Login'                         => __DIR__ . '/src/Application/Form/Login.php',
    'Application\Form\UsuarioEditarSenhaForm'        => __DIR__ . '/src/Application/Form/UsuarioEditarSenhaForm.php',
    'Application\Form\UsuarioEditarSenhaFilter'      => __DIR__ . '/src/Application/Form/UsuarioEditarSenhaFilter.php',
    'ApplicationTest\Controller\IndexControllerTest' => __DIR__ . '/tests/src/Application/Controller/IndexControllerTest.php',
    'ApplicationTest\Controller\AuthControllerTest'  => __DIR__ . '/tests/src/Application/Controller/AuthControllerTest.php',
    'ApplicationTest\Bootstrap'                      => __DIR__ . '/tests/Bootstrap.php',
    'Application\Module'                             => __DIR__ . '/Module.php',
);
