<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'partials/paginacao/paginacao'      => __DIR__ . '/view/partials/paginacao/paginacao.phtml',
    'error/index'                       => __DIR__ . '/view/error/index.phtml',
    'error/404'                         => __DIR__ . '/view/error/404.phtml',
    'layout/login'                      => __DIR__ . '/view/layout/login.phtml',
    'layout/layout'                     => __DIR__ . '/view/layout/layout.phtml',
    'layout/footer'                     => __DIR__ . '/view/layout/footer.phtml',
    'application/index/index'           => __DIR__ . '/view/application/index/index.phtml',
    'application/index/about'           => __DIR__ . '/view/application/index/about.phtml',
    'application/usuario/index'         => __DIR__ . '/view/application/usuario/index.phtml',
    'application/usuario/salvar'        => __DIR__ . '/view/application/usuario/salvar.phtml',
    'application/usuario/editar-senha'  => __DIR__ . '/view/application/usuario/editar-senha.phtml',
    'application/auth/permissao-negada' => __DIR__ . '/view/application/auth/permissao-negada.phtml',
    'application/auth/login'            => __DIR__ . '/view/application/auth/login.phtml',
);
