<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Coreproc\Module'      => __DIR__ . '/Module.php',
    'Coreproc\CryptoGuard' => __DIR__ . '/src/Coreproc/CryptoGuard.php',
    'CryptoGuardTest'      => __DIR__ . '/tests/CryptoGuardTest.php',
);
