
<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('home') ?>">Início</a></li>
    <li class="active">Servidor</li>
</ol>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <h3>Servidor</h3>
    </div>
    <div class="col-sm-6 col-md-6">
        <div class="btn-group pull-right">
            <a href="<?php echo $this->url('servidor', array(
                'action' => 'criar'
            )) ?>" class="btn btn-primary btn-lg">
                <i class="fa fa-plus"></i>
				Servidor
            </a>
        </div>
    </div>
</div>
