<?php
    $this->headScript()->appendFile($this->basePath() . '/lib/js/momentjs/moment-with-locales.min.js');
    $this->headScript()->appendFile($this->basePath() . '/js/application/familiar/index.js');
?>

<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('home') ?>">Início</a></li>
    <li class="active">Dados Familiares</li>
</ol>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <h3>Dados Familiares</h3>
    </div>
    <div class="col-sm-6 col-md-6">
        <div class="btn-group pull-right">
            <a href="<?php echo $this->url('familiar', array('action' => 'criar', 'id_pessoa' => $id_pessoa,)) ?>" class="btn btn-primary btn-lg">
                <i class="fa fa-plus"></i>
                Familiar
            </a>
        </div>
    </div>

</div>

<hr/>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <form method="get" role="form">
            <div class="row">
                <div class="col-sm-8 col-md-6">
                    <input type="text" name="restricao" autofocus="autofocus" value="<?php echo $this->restricao ?>"
                           class="form-control" placeholder="Buscar...">
                </div>
                <div class="col-sm-3 col-md-3">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Profissão</th>
                    <th>Grau de Parentesco</th>
                    <th>Mora</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

            <?php foreach($list as $item): ?>

                <tr>
                    <td>

                        <?php echo $item['nome']; ?>
                    </td>
                    <td>
                        <?php echo $item['idade']; ?>
                    </td>
                    <td>
                        <?php echo $item['profissao']; ?>
                    </td>
                    <td>
                        <?php echo $item['grau_parentesco']; ?>
                    </td>
                    <td>
                        <?php if($item['flMora']):  ?>
                            Sim
                        <?php else:  ?>
                            Não
                        <?php endif;  ?>
                    </td>
                    <td>
                        <div class="btn-group">
                            <a href="<?php echo $this->url('familiar', array(
                                'action' => 'editar',
                                'id' => $item['id'],
                                'id_pessoa' => $item['id_pessoa'],
                            )) ?>" class="btn btn-default">
                                <i class="fa fa-edit"></i> Editar
                            </a>
                        </div>
                    </td>

                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
