<?php
	$this->headLink()->appendStylesheet($this->basePath() . '/lib/css/select2/select2.css');
	$this->headLink()->appendStylesheet($this->basePath() . '/lib/css/select2-bootstrap3-css/select2-bootstrap.css');
	$this->headScript()->appendFile($this->basePath() . '/lib/js/select2/select2.min.js');

	$this->headLink()->prependStylesheet($this->basePath() . '/lib/css/bootstrap-datetimepicker/bootstrap-datetimepicker.min.css');

	$this->headScript()->appendFile($this->basePath() . '/lib/js/momentjs/moment-with-locales.min.js');
	$this->headScript()->appendFile($this->basePath() . '/lib/js/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js');
	$this->headScript()->appendFile($this->basePath() . '/lib/js/jquery-maskedinput/jquery.maskedinput.min.js');

	$this->headScript()->appendFile($this->basePath() . '/js/application/aluno/salvar.js');
?>

<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('home') ?>">Início</a></li>
    <li><a href="<?php echo $this->url('aluno') ?>">Aluno</a></li>
    <li class="active"><?php echo $title ?></li>
</ol>

<h4><?php echo $title ?></h4><hr/>

<?php
$form->prepare();
echo $this->form()->openTag($form);
?>

<div class="row">
    <div class="col-sm-2 col-md-2">
        <div class="form-group">
            <?php echo $this->formRow($form->get('matricula')); ?>
        </div>
    </div>

    <div class="col-sm-6 col-md-6">
        <div class="form-group">
            <?php echo $this->formLabel($form->get('id_curso')); ?>
            <?php echo $this->formInput($form->get('id_curso')); ?>
            <div class="form-errors">
                <?php echo $this->formElementErrors($form->get('id_curso')); ?>
            </div>
        </div>
    </div>
</div>


<?php echo $this->partial('partials/pessoa/salvar.phtml', array(
    'form' => $form,
)); ?>


<div class="row">
    <div class="col-sm-6 col-md-6">
        <div class="form-group">
            <?php echo $this->formLabel($form->get('situacao_escolar')); ?>
            <?php echo $this->formTextarea($form->get('situacao_escolar')); ?>
            <div class="form-errors">
                <?php echo $this->formElementErrors($form->get('situacao_escolar')); ?>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-8">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php
    echo $this->form()->closeTag();
?>
