<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZealMessages\Module'                     => __DIR__ . '/Module.php',
    'ZealMessages\Controller\Plugin\Messages' => __DIR__ . '/src/ZealMessages/Controller/Plugin/Messages.php',
    'ZealMessages\View\Helper\Messages'       => __DIR__ . '/src/ZealMessages/View/Helper/Messages.php',
);
