<?php
    $this->headLink()->prependStylesheet($this->basePath() . '/css/grid-menu.css')
?>

<ol class="breadcrumb">
    <li class="active">Painel Administrativo</li>
</ol>

<div class="row">
    <div class="col-md-12">
        <ul class="grid-menu">

            <li rel="tooltip" title="Profissão">
                <a href="<?php echo $this->url('profissao') ?>">
                    <img src="<?php echo $this->basePath() . '/images/admin/index/index/profissao.png' ?>"
                         alt="Profissão" class="center"/>
                </a>
            </li>

            <li rel="tooltip" title="Cargo">
                <a href="<?php echo $this->url('cargo') ?>">
                    <img src="<?php echo $this->basePath() . '/images/admin/index/index/cargo.png' ?>"
                         alt="Cargo" class="center"/>
                </a>
            </li>

            <li rel="tooltip" title="Servidor">
                <a href="<?php echo $this->url('servidor') ?>">
                    <img src="<?php echo $this->basePath() . '/images/admin/index/index/servidor.png' ?>"
                         alt="Servidor" class="center"/>
                </a>
            </li>

        </ul>
    </div>
</div>
