<div id="toolbar" class="toolbar ql-toolbar ql-snow">
    <span class="ql-format-group">
        <select title="Tamanho" class="ql-size">
            <option value="10px">Pequeno</option>
            <option value="13px" selected="">Normal</option>
            <option value="18px">Grande</option>
            <option value="32px">Enorme</option>
        </select>
    </span>
    <span class="ql-format-group">
        <span title="Negrito" class="ql-format-button ql-bold"></span>
        <span class="ql-format-separator"></span>
        <span title="Itálico" class="ql-format-button ql-italic"></span>
        <span class="ql-format-separator"></span>
        <span title="Underline" class="ql-format-button ql-underline"></span>
        <span class="ql-format-separator"></span>
        <span title="Strikethrough" class="ql-format-button ql-strike"></span>
    </span>
    <span class="ql-format-group">
        <span title="Lista" class="ql-format-button ql-list"></span>
        <span class="ql-format-separator"></span>
        <span title="Bullet" class="ql-format-button ql-bullet"></span>
        <span class="ql-format-separator"></span>
        <select title="Alinhamento" class="ql-align">
            <option value="left" label="Esquerda" selected=""></option>
            <option value="center" label="Centro"></option>
            <option value="right" label="Direita"></option>
            <option value="justify" label="Justificado"></option>
        </select>
    </span>
    <span class="ql-format-group">
        <span title="Link" class="ql-format-button ql-link"></span>
    </span>
    <div class="btn-group pull-right">
        <button class="btn btn-primary btn-sm" id="btn-salvar" title="Ctrl + S">
            <i class="fa fa-save"></i> Salvar
        </button>
    </div>
</div>
